using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using STEP.Application.Common.Interfaces;

namespace STEP.Infrastructure.Documents
{
    public class QuestPdfOfferLetterGenerator : IOfferLetterPdfGenerator
    {
        static QuestPdfOfferLetterGenerator()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public byte[] Generate(OfferLetterPdfModel model)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Header().Column(col =>
                    {
                        col.Item().Text("STEP Enterprise ATS").FontSize(18).Bold();
                        col.Item().Text("Offer of Employment").FontSize(13).SemiBold();
                        col.Item().PaddingTop(4).LineHorizontal(1);
                    });

                    page.Content().PaddingVertical(20).Column(col =>
                    {
                        col.Spacing(12);

                        col.Item().Text($"Date: {model.GeneratedAt:dd MMMM yyyy}");
                        col.Item().Text($"Dear {model.CandidateName},");

                        col.Item().Text(
                            $"We are pleased to offer you the position of \"{model.VacancyTitle}\" ({model.EmploymentType}) " +
                            "with STEP Enterprise. This letter outlines the key terms of your offer.");

                        col.Item().PaddingTop(8).Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.ConstantColumn(160);
                                columns.RelativeColumn();
                            });

                            void Row(string label, string value)
                            {
                                table.Cell().Text(label).SemiBold();
                                table.Cell().Text(value);
                            }

                            Row("Position", model.VacancyTitle);
                            Row("Employment Type", model.EmploymentType);
                            Row("Annual CTC", $"₹ {model.OfferedCTC:N2}");
                            Row("Joining Date", model.JoiningDate.ToString("dd MMMM yyyy"));
                        });

                        col.Item().PaddingTop(8).Text(
                            "This offer is contingent upon successful completion of your background verification " +
                            "and reference checks. Please confirm your acceptance by replying to this communication.");

                        col.Item().PaddingTop(20).Text("Warm regards,");
                        col.Item().Text(model.PreparedByName).SemiBold();
                        col.Item().Text("On behalf of STEP Enterprise ATS");
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by STEP Enterprise ATS — ").FontSize(8);
                        x.Span(model.GeneratedAt.ToString("u")).FontSize(8);
                    });
                });
            });

            return document.GeneratePdf();
        }
    }
}
