using System;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Microsoft.EntityFrameworkCore;
using STEP.Application.Common.Exceptions;
using STEP.Application.Common.Interfaces;
using STEP.Application.Features.Interviews.Common;
using STEP.Domain.Entities.Interview;
using CandidateEntity = STEP.Domain.Entities.Candidate.Candidate;

namespace STEP.Application.Features.Interviews.Commands.ScheduleInterview
{
    public class ScheduleInterviewCommandHandler(
        IApplicationDbContext db,
        IInterviewerNotificationService notificationService,
        ICurrentUserService? currentUserService = null) : IRequestHandler<ScheduleInterviewCommand, InterviewDto>
    {
        public async Task<InterviewDto> Handle(ScheduleInterviewCommand request, CancellationToken cancellationToken)
        {
            var candidate = await db.Candidates
                .Include(c => c.Vacancy)
                .Include(c => c.CurrentPipelineProgress)
                .Include(c => c.PipelineProgressHistory)
                .FirstOrDefaultAsync(c => c.Id == request.CandidateId, cancellationToken)
                ?? throw new NotFoundException(nameof(CandidateEntity), request.CandidateId);

            var interviewerExists = await db.Users.AnyAsync(u => u.Id == request.InterviewerUserId, cancellationToken);
            if (!interviewerExists)
            {
                throw new NotFoundException(nameof(STEP.Domain.Entities.Identity.User), request.InterviewerUserId);
            }

            // Find target pipeline progress round
            STEP.Domain.Entities.Candidate.CandidatePipelineProgress? progress = null;

            if (request.RoundNumber.HasValue)
            {
                progress = candidate.PipelineProgressHistory.FirstOrDefault(p => p.RoundNumber == request.RoundNumber.Value);
            }

            if (progress == null)
            {
                progress = candidate.PipelineProgressHistory
                    .Where(p => (p.RoundType == "Interview" || p.RoundType == "Director" || (p.RoundTitle ?? "").Contains("Interview", StringComparison.OrdinalIgnoreCase)) && p.Status != "Passed")
                    .OrderBy(p => p.RoundNumber)
                    .FirstOrDefault()
                    ?? candidate.CurrentPipelineProgress;
            }

            if (progress == null)
            {
                var defaultFlow = await db.VacancyPipelineFlows
                    .Include(f => f.Rounds)
                    .FirstOrDefaultAsync(f => f.VacancyId == candidate.VacancyId && f.IsDefault && !f.IsDeleted, cancellationToken)
                    ?? await db.VacancyPipelineFlows
                    .Include(f => f.Rounds)
                    .FirstOrDefaultAsync(f => f.VacancyId == candidate.VacancyId && !f.IsDeleted, cancellationToken);

                var targetRound = defaultFlow?.Rounds?.FirstOrDefault(r => request.RoundNumber.HasValue ? r.RoundOrder == request.RoundNumber.Value : (r.RoundType == "Interview" || r.RoundType == "Director"))
                    ?? defaultFlow?.Rounds?.OrderByDescending(r => r.RoundOrder).FirstOrDefault();

                if (targetRound != null)
                {
                    progress = new STEP.Domain.Entities.Candidate.CandidatePipelineProgress
                    {
                        CandidateId = candidate.Id,
                        VacancyPipelineFlowRoundId = targetRound.Id,
                        RoundNumber = targetRound.RoundOrder,
                        RoundTitle = targetRound.Name,
                        RoundType = targetRound.RoundType,
                        Status = "InProgress",
                        StartedAt = DateTime.UtcNow,
                    };
                    db.CandidatePipelineProgresses.Add(progress);
                    candidate.PipelineProgressHistory.Add(progress);
                }
            }

            if (progress == null)
            {
                throw new ValidationException([new FluentValidation.Results.ValidationFailure("CurrentPipelineProgress",
                    "Unable to find or initialize an interview round for this candidate.")]);
            }

            progress.EvaluatorId = request.InterviewerUserId;
            if (progress.Status == "Pending" || string.IsNullOrWhiteSpace(progress.Status))
            {
                progress.Status = "InProgress";
            }
            progress.StartedAt ??= DateTime.UtcNow;
            candidate.CurrentPipelineProgress = progress;

            // Save progress changes first so progress.Id is generated by database if new
            await db.SaveChangesAsync(cancellationToken);

            // Reassigning/rescheduling an already-scheduled round updates that same Interview row
            var interview = await db.Interviews
                .Where(i => i.CandidateId == candidate.Id && (i.CandidatePipelineProgressId == progress.Id || i.CandidatePipelineProgressId == 0) && i.Status != "Cancelled")
                .OrderByDescending(i => i.Id)
                .FirstOrDefaultAsync(cancellationToken);

            if (interview == null)
            {
                interview = new Interview
                {
                    CandidatePipelineProgressId = progress.Id,
                    CandidateId = candidate.Id,
                };
                db.Interviews.Add(interview);
            }
            else
            {
                interview.CandidatePipelineProgressId = progress.Id;
            }

            interview.InterviewerUserId = request.InterviewerUserId;
            interview.ScheduledAt = request.ScheduledAt;
            interview.DurationMinutes = request.DurationMinutes;
            interview.Mode = request.Mode;
            interview.MeetingLinkOrLocation = request.MeetingLinkOrLocation;
            interview.Status = "Scheduled";

            await db.SaveChangesAsync(cancellationToken);

            var interviewer = await db.Users.FirstAsync(u => u.Id == request.InterviewerUserId, cancellationToken);

            var teamsChatLink = notificationService.GenerateTeamsDirectChatLink(
                interviewerEmail: interviewer.Email,
                interviewerFirstName: interviewer.FirstName,
                candidateName: $"{candidate.FirstName} {candidate.LastName}".Trim(),
                candidateCode: candidate.CandidateCode,
                vacancyTitle: candidate.Vacancy?.Title ?? "Position",
                roundTitle: progress.RoundTitle ?? "Technical Interview",
                experienceYears: candidate.TotalExperienceYears,
                candidateId: candidate.Id,
                mode: interview.Mode,
                meetingLink: interview.MeetingLinkOrLocation);

            try
            {
                var currentHrEmail = currentUserService?.Email;
                var currentHrName = currentUserService?.UserId != null ? $"HR Recruiter #{currentUserService.UserId}" : null;

                await notificationService.SendInterviewNotificationsAsync(
                    interview.Id,
                    currentHrEmail,
                    currentHrName,
                    cancellationToken);
            }
            catch
            {
                // Notifications shouldn't fail the primary scheduling transaction
            }

            return new InterviewDto(
                interview.Id, candidate.Id, $"{candidate.FirstName} {candidate.LastName}", candidate.Vacancy?.Title ?? "Position",
                interview.InterviewerUserId, $"{interviewer.FirstName} {interviewer.LastName}",
                interview.ScheduledAt, interview.DurationMinutes, interview.Mode, interview.MeetingLinkOrLocation,
                interview.Status, [],
                TeamsChatLink: teamsChatLink,
                InterviewerEmail: interviewer.Email);
        }
    }
}
