export interface MockPipelineProgress {
  id: number;
  roundNumber: number;
  roundTitle: string;
  roundType: 'Assessment' | 'Interview';
  status: 'Passed' | 'Failed' | 'In-Progress' | 'Scheduled' | 'Pending' | 'Terminated' | 'Locked';
  scoreObtained: number | null;
  startedAt: string | null;
  completedAt: string | null;
  candidateExamSessionId: number | null;
  interviewId: number | null;
}

export interface MockCandidateDocument {
  id: number;
  documentType: string;
  name: string;
  originalFileName: string;
  uploadedAt: string;
  fileSizeBytes: number;
  storageUrl: string;
}

export interface MockCandidate {
  id: number;
  candidateCode: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  gender: 'Male' | 'Female' | 'Other';
  dateOfBirth: string;
  currentLocation: string;
  hiringLocation: string;
  testLocation: string;
  role: string;
  vacancyId: number;
  vacancyTitle: string;
  experienceYears: number;
  totalExperienceYears: number;
  registrationChannel: 'Walk-in' | 'Portal' | 'Direct';
  currentStage: string;
  status: 'Applied' | 'In-Progress' | 'Offered' | 'On Hold' | 'Rejected' | 'Hired';
  currentCompany?: string;
  currentDesignation?: string;
  currentCTC?: number;
  expectedCTC?: number;
  noticePeriodDays?: number;
  highestQualification?: string;
  institutionName?: string;
  yearOfPassing?: number;
  assignedInterviewer?: string;
  createdAt: string;
  updatedAt: string;
  avatarUrl?: string;
  pipelineProgress: MockPipelineProgress[];
  documents: MockCandidateDocument[];
}

export const MOCK_CANDIDATES: MockCandidate[] = [
  {
    id: 1,
    candidateCode: 'CND-2026-1001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 98201 23456',
    gender: 'Male',
    dateOfBirth: '1995-04-12',
    currentLocation: 'Mumbai',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 6,
    totalExperienceYears: 6,
    registrationChannel: 'Walk-in',
    currentStage: 'Interview',
    status: 'In-Progress',
    currentCompany: 'Infosys Limited',
    currentDesignation: 'Senior Lead Software Engineer',
    currentCTC: 22,
    expectedCTC: 28,
    noticePeriodDays: 30,
    highestQualification: 'B.Tech in Computer Science',
    institutionName: 'VJTI Mumbai',
    yearOfPassing: 2017,
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-01-18T10:30:00Z',
    updatedAt: '2026-01-20T16:00:00Z',
    pipelineProgress: [
      {
        id: 1,
        roundNumber: 1,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 88,
        startedAt: '2026-01-19T10:00:00Z',
        completedAt: '2026-01-19T11:00:00Z',
        candidateExamSessionId: 1001,
        interviewId: null,
      },
      {
        id: 2,
        roundNumber: 2,
        roundTitle: 'Technical Architecture Interview',
        roundType: 'Interview',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-01-22T14:30:00Z',
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: 2001,
      },
      {
        id: 3,
        roundNumber: 3,
        roundTitle: 'Director & Leadership Round',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Resume',
        name: 'Aarav_Sharma_CV_2026.pdf',
        originalFileName: 'Aarav_Sharma_CV_2026.pdf',
        uploadedAt: '2026-01-18T10:32:00Z',
        fileSizeBytes: 245000,
        storageUrl: '/mock-documents/resume_aarav.pdf',
      },
      {
        id: 2,
        documentType: 'Govt ID',
        name: 'Aadhaar_Card.pdf',
        originalFileName: 'Aadhaar_Card.pdf',
        uploadedAt: '2026-01-18T10:35:00Z',
        fileSizeBytes: 412000,
        storageUrl: '/mock-documents/id_aarav.pdf',
      },
    ],
  },
  {
    id: 2,
    candidateCode: 'CND-2026-1002',
    firstName: 'Ananya',
    lastName: 'Iyer',
    email: 'ananya.iyer@example.com',
    phone: '+91 98450 78912',
    gender: 'Female',
    dateOfBirth: '1998-08-25',
    currentLocation: 'Pune',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Full Stack React / Node Lead Developer',
    vacancyId: 2,
    vacancyTitle: 'Full Stack React / Node Lead Developer',
    experienceYears: 4,
    totalExperienceYears: 4,
    registrationChannel: 'Walk-in',
    currentStage: 'Director Round',
    status: 'In-Progress',
    currentCompany: 'Persistent Systems',
    currentDesignation: 'Senior Frontend Developer',
    currentCTC: 16,
    expectedCTC: 21,
    noticePeriodDays: 15,
    highestQualification: 'B.E. in Information Technology',
    institutionName: 'COEP Pune',
    yearOfPassing: 2020,
    assignedInterviewer: 'Rajesh Kulkarni',
    createdAt: '2026-01-22T09:15:00Z',
    updatedAt: '2026-01-25T17:30:00Z',
    pipelineProgress: [
      {
        id: 4,
        roundNumber: 1,
        roundTitle: 'Frontend & Full Stack Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 92,
        startedAt: '2026-01-23T11:00:00Z',
        completedAt: '2026-01-23T11:45:00Z',
        candidateExamSessionId: 1002,
        interviewId: null,
      },
      {
        id: 5,
        roundNumber: 2,
        roundTitle: 'Coding & System Design Interview',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: 90,
        startedAt: '2026-01-24T15:00:00Z',
        completedAt: '2026-01-24T15:45:00Z',
        candidateExamSessionId: null,
        interviewId: 2002,
      },
      {
        id: 6,
        roundNumber: 3,
        roundTitle: 'HR & Management Round',
        roundType: 'Interview',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-01-26T16:00:00Z',
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: 2003,
      },
    ],
    documents: [
      {
        id: 3,
        documentType: 'Resume',
        name: 'Ananya_Iyer_FullStack.pdf',
        originalFileName: 'Ananya_Iyer_FullStack.pdf',
        uploadedAt: '2026-01-22T09:20:00Z',
        fileSizeBytes: 310000,
        storageUrl: '/mock-documents/resume_ananya.pdf',
      },
    ],
  },
  {
    id: 3,
    candidateCode: 'CND-2026-1003',
    firstName: 'Rohan',
    lastName: 'Kulkarni',
    email: 'rohan.k@example.com',
    phone: '+91 97631 44556',
    gender: 'Male',
    dateOfBirth: '1993-11-04',
    currentLocation: 'Mumbai',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 8,
    totalExperienceYears: 8,
    registrationChannel: 'Direct',
    currentStage: 'Offered',
    status: 'Offered',
    currentCompany: 'Capgemini',
    currentDesignation: 'Solutions Architect',
    currentCTC: 28,
    expectedCTC: 35,
    noticePeriodDays: 0,
    highestQualification: 'M.Tech in Software Engineering',
    institutionName: 'IIT Bombay',
    yearOfPassing: 2016,
    assignedInterviewer: 'Priya Sharma',
    createdAt: '2026-01-16T14:00:00Z',
    updatedAt: '2026-01-26T18:00:00Z',
    pipelineProgress: [
      {
        id: 7,
        roundNumber: 1,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 95,
        startedAt: '2026-01-17T10:00:00Z',
        completedAt: '2026-01-17T11:00:00Z',
        candidateExamSessionId: 1003,
        interviewId: null,
      },
      {
        id: 8,
        roundNumber: 2,
        roundTitle: 'Technical Architecture Interview',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: 92,
        startedAt: '2026-01-20T11:00:00Z',
        completedAt: '2026-01-20T11:50:00Z',
        candidateExamSessionId: null,
        interviewId: 2004,
      },
      {
        id: 9,
        roundNumber: 3,
        roundTitle: 'Director & Leadership Round',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: 96,
        startedAt: '2026-01-24T14:00:00Z',
        completedAt: '2026-01-24T14:35:00Z',
        candidateExamSessionId: null,
        interviewId: 2005,
      },
    ],
    documents: [
      {
        id: 4,
        documentType: 'Resume',
        name: 'Rohan_Kulkarni_Architect.pdf',
        originalFileName: 'Rohan_Kulkarni_Architect.pdf',
        uploadedAt: '2026-01-16T14:05:00Z',
        fileSizeBytes: 290000,
        storageUrl: '/mock-documents/resume_rohan.pdf',
      },
      {
        id: 5,
        documentType: 'Offer Letter',
        name: 'Offer_Letter_Rohan_Kulkarni.pdf',
        originalFileName: 'Offer_Letter_Rohan_Kulkarni.pdf',
        uploadedAt: '2026-01-26T18:15:00Z',
        fileSizeBytes: 520000,
        storageUrl: '/mock-documents/offer_rohan.pdf',
      },
    ],
  },
  {
    id: 4,
    candidateCode: 'CND-2026-1004',
    firstName: 'Sneha',
    lastName: 'Patel',
    email: 'sneha.patel@example.com',
    phone: '+91 99887 11223',
    gender: 'Female',
    dateOfBirth: '1999-03-18',
    currentLocation: 'Bengaluru',
    hiringLocation: 'Bengaluru Tech Hub',
    testLocation: 'Bengaluru Assessment Center',
    role: 'QA Automation Lead (Playwright & Selenium)',
    vacancyId: 3,
    vacancyTitle: 'QA Automation Lead (Playwright & Selenium)',
    experienceYears: 3,
    totalExperienceYears: 3,
    registrationChannel: 'Portal',
    currentStage: 'Assessment',
    status: 'In-Progress',
    currentCompany: 'Wipro',
    currentDesignation: 'QA Automation Engineer',
    currentCTC: 12,
    expectedCTC: 16,
    noticePeriodDays: 30,
    highestQualification: 'B.Tech in Computer Engineering',
    institutionName: 'NIT Surathkal',
    yearOfPassing: 2021,
    assignedInterviewer: 'Amit Patel',
    createdAt: '2026-02-03T11:00:00Z',
    updatedAt: '2026-02-04T12:00:00Z',
    pipelineProgress: [
      {
        id: 10,
        roundNumber: 1,
        roundTitle: 'Automation & Testing Assessment',
        roundType: 'Assessment',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-02-04T10:00:00Z',
        completedAt: null,
        candidateExamSessionId: 1004,
        interviewId: null,
      },
      {
        id: 11,
        roundNumber: 2,
        roundTitle: 'Hands-on Framework Interview',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [],
  },
  {
    id: 5,
    candidateCode: 'CND-2026-1005',
    firstName: 'Devendra',
    lastName: 'Pandey',
    email: 'devendra.p@example.com',
    phone: '+91 94220 99887',
    gender: 'Male',
    dateOfBirth: '1996-07-30',
    currentLocation: 'Mumbai',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Cloud DevOps & Kubernetes Specialist',
    vacancyId: 4,
    vacancyTitle: 'Cloud DevOps & Kubernetes Specialist',
    experienceYears: 5,
    totalExperienceYears: 5,
    registrationChannel: 'Direct',
    currentStage: 'Joined',
    status: 'Hired',
    currentCompany: 'Accenture',
    currentDesignation: 'DevOps Lead',
    currentCTC: 20,
    expectedCTC: 26,
    noticePeriodDays: 0,
    highestQualification: 'B.E. in Electronics & Telecom',
    institutionName: 'Mumbai University',
    yearOfPassing: 2018,
    assignedInterviewer: 'Priya Sharma',
    createdAt: '2026-01-10T09:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    pipelineProgress: [
      {
        id: 12,
        roundNumber: 1,
        roundTitle: 'Cloud Architecture Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 85,
        startedAt: '2026-01-12T10:00:00Z',
        completedAt: '2026-01-12T11:00:00Z',
        candidateExamSessionId: 1005,
        interviewId: null,
      },
      {
        id: 13,
        roundNumber: 2,
        roundTitle: 'Live Infrastructure Debugging Interview',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: 94,
        startedAt: '2026-01-15T15:00:00Z',
        completedAt: '2026-01-15T16:00:00Z',
        candidateExamSessionId: null,
        interviewId: 2006,
      },
    ],
    documents: [],
  },
  {
    id: 6,
    candidateCode: 'CND-2026-1006',
    firstName: 'Tanvi',
    lastName: 'Mehta',
    email: 'tanvi.m@example.com',
    phone: '+91 98190 33445',
    gender: 'Female',
    dateOfBirth: '2001-09-14',
    currentLocation: 'Pune',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Full Stack React / Node Lead Developer',
    vacancyId: 2,
    vacancyTitle: 'Full Stack React / Node Lead Developer',
    experienceYears: 1,
    totalExperienceYears: 1,
    registrationChannel: 'Walk-in',
    currentStage: 'Screening',
    status: 'Rejected',
    currentCompany: 'TCS',
    currentDesignation: 'Assistant System Engineer',
    currentCTC: 4.5,
    expectedCTC: 8,
    noticePeriodDays: 60,
    highestQualification: 'B.Tech in Information Technology',
    institutionName: 'Pune University',
    yearOfPassing: 2024,
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-01-24T14:00:00Z',
    updatedAt: '2026-01-25T11:00:00Z',
    pipelineProgress: [
      {
        id: 14,
        roundNumber: 1,
        roundTitle: 'Frontend & Full Stack Assessment',
        roundType: 'Assessment',
        status: 'Failed',
        scoreObtained: 42,
        startedAt: '2026-01-25T10:00:00Z',
        completedAt: '2026-01-25T10:45:00Z',
        candidateExamSessionId: 1006,
        interviewId: null,
      },
    ],
    documents: [],
  },
  {
    id: 7,
    candidateCode: 'CND-2026-1007',
    firstName: 'Karan',
    lastName: 'Singhania',
    email: 'karan.singh@example.com',
    phone: '+91 97110 55667',
    gender: 'Male',
    dateOfBirth: '1997-02-10',
    currentLocation: 'Mumbai',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 4,
    totalExperienceYears: 4,
    registrationChannel: 'Walk-in',
    currentStage: 'Screening',
    status: 'On Hold',
    currentCompany: 'LTI Mindtree',
    currentDesignation: 'Software Specialist',
    currentCTC: 15,
    expectedCTC: 20,
    noticePeriodDays: 90,
    highestQualification: 'MCA',
    institutionName: 'SNDT Mumbai',
    yearOfPassing: 2019,
    assignedInterviewer: 'Priya Sharma',
    createdAt: '2026-01-28T09:30:00Z',
    updatedAt: '2026-01-29T14:00:00Z',
    pipelineProgress: [
      {
        id: 15,
        roundNumber: 1,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'In-Progress',
        scoreObtained: 68,
        startedAt: '2026-01-29T11:00:00Z',
        completedAt: '2026-01-29T12:00:00Z',
        candidateExamSessionId: 1007,
        interviewId: null,
      },
    ],
    documents: [],
  },
];
