export interface MockPipelineProgress {
  id: number;
  roundNumber: number;
  roundTitle: string;
  roundType: 'Assessment' | 'Interview';
  status: 'Passed' | 'Failed' | 'In-Progress' | 'Scheduled' | 'Pending' | 'Terminated' | 'Locked';
  scoreObtained: number | null;
  startedAt: string | null;
  completedAt: string | null;
  candidateExamSessionId: number | null;
  interviewId: number | null;
}

export interface MockCandidateDocument {
  id: number;
  documentType: string;
  name: string;
  originalFileName: string;
  uploadedAt: string;
  fileSizeBytes: number;
  storageUrl: string;
}

export interface MockCandidate {
  id: number;
  candidateCode: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  gender: 'Male' | 'Female' | 'Other';
  dateOfBirth: string;
  currentLocation: string;
  hiringLocation: string;
  testLocation: string;
  role: string;
  vacancyId: number;
  vacancyTitle: string;
  experienceYears: number;
  totalExperienceYears: number;
  registrationChannel: 'Walk-in' | 'Portal' | 'Direct';
  currentStage: string;
  status: 'Applied' | 'In-Progress' | 'Offered' | 'On Hold' | 'Rejected' | 'Hired';
  currentCompany?: string;
  currentDesignation?: string;
  currentCTC?: number;
  expectedCTC?: number;
  noticePeriodDays?: number;
  highestQualification?: string;
  institutionName?: string;
  yearOfPassing?: number;
  marksPercentage?: number;
  refType?: 'Direct' | 'Internal' | 'External';
  refName?: string;
  refMobile?: string;
  assignedInterviewer?: string;
  createdAt: string;
  updatedAt: string;
  avatarUrl?: string;
  pipelineProgress: MockPipelineProgress[];
  documents: MockCandidateDocument[];
}

export const MOCK_CANDIDATES: MockCandidate[] = [
  {
    id: 1,
    candidateCode: 'CND-2026-1001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav.sharma@example.com',
    phone: '9820123456',
    gender: 'Male',
    dateOfBirth: '1995-04-12',
    currentLocation: 'Mumbai, Maharashtra',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 6,
    totalExperienceYears: 6,
    registrationChannel: 'Walk-in',
    currentStage: 'Technical Architecture Interview',
    status: 'In-Progress',
    currentCompany: 'Infosys Limited',
    currentDesignation: 'Lead Software Engineer',
    currentCTC: 22,
    expectedCTC: 28,
    noticePeriodDays: 30,
    highestQualification: 'B.Tech in Computer Science',
    institutionName: 'VJTI Mumbai',
    yearOfPassing: 2018,
    marksPercentage: 86.5,
    refType: 'Internal',
    refName: 'Vikram Deshmukh',
    refMobile: '9876501122',
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-01-18T10:30:00Z',
    updatedAt: '2026-01-20T16:00:00Z',
    pipelineProgress: [
      {
        id: 1,
        roundNumber: 1,
        roundTitle: 'Aptitude & General Elimination',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 88,
        startedAt: '2026-01-19T10:00:00Z',
        completedAt: '2026-01-19T10:45:00Z',
        candidateExamSessionId: 9001,
        interviewId: null,
      },
      {
        id: 2,
        roundNumber: 2,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 88,
        startedAt: '2026-01-20T14:30:00Z',
        completedAt: '2026-01-20T15:30:00Z',
        candidateExamSessionId: 1001,
        interviewId: null,
      },
      {
        id: 3,
        roundNumber: 3,
        roundTitle: 'Technical Architecture Interview',
        roundType: 'Interview',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-01-22T14:30:00Z',
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: 2001,
      },
      {
        id: 4,
        roundNumber: 4,
        roundTitle: 'Director & Final Offer Decision',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 1,
        documentType: 'Resume',
        name: 'Aarav_Sharma_CV_2026.pdf',
        originalFileName: 'Aarav_Sharma_CV_2026.pdf',
        uploadedAt: '2026-01-18T10:32:00Z',
        fileSizeBytes: 245000,
        storageUrl: '/mock-documents/resume_aarav.pdf',
      },
    ],
  },
  {
    id: 2,
    candidateCode: 'CND-2026-1002',
    firstName: 'Ananya',
    lastName: 'Iyer',
    email: 'ananya.iyer@example.com',
    phone: '9845078912',
    gender: 'Female',
    dateOfBirth: '1998-08-25',
    currentLocation: 'Pune, Maharashtra',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Full Stack React / Node Lead Developer',
    vacancyId: 2,
    vacancyTitle: 'Full Stack React / Node Lead Developer',
    experienceYears: 4,
    totalExperienceYears: 4,
    registrationChannel: 'Walk-in',
    currentStage: 'Director Round',
    status: 'In-Progress',
    currentCompany: 'Persistent Systems',
    currentDesignation: 'Senior Frontend Developer',
    currentCTC: 16,
    expectedCTC: 21,
    noticePeriodDays: 15,
    highestQualification: 'B.E. in Information Technology',
    institutionName: 'COEP Technological University',
    yearOfPassing: 2020,
    marksPercentage: 89.2,
    refType: 'Direct',
    assignedInterviewer: 'Rajesh Kulkarni',
    createdAt: '2026-01-22T09:15:00Z',
    updatedAt: '2026-01-25T17:30:00Z',
    pipelineProgress: [
      {
        id: 5,
        roundNumber: 1,
        roundTitle: 'Aptitude & Logical Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 94,
        startedAt: '2026-01-23T11:00:00Z',
        completedAt: '2026-01-23T11:45:00Z',
        candidateExamSessionId: 9001,
        interviewId: null,
      },
      {
        id: 6,
        roundNumber: 2,
        roundTitle: 'React & Full Stack Technical Exam',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 91,
        startedAt: '2026-01-24T10:00:00Z',
        completedAt: '2026-01-24T11:00:00Z',
        candidateExamSessionId: 1002,
        interviewId: null,
      },
      {
        id: 7,
        roundNumber: 3,
        roundTitle: 'Live Coding & F2F Technical Interview',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: null,
        startedAt: '2026-01-25T14:00:00Z',
        completedAt: '2026-01-25T15:00:00Z',
        candidateExamSessionId: null,
        interviewId: 2002,
      },
      {
        id: 8,
        roundNumber: 4,
        roundTitle: 'Director Decision & Offer Rollout',
        roundType: 'Interview',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-01-26T16:00:00Z',
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: 2003,
      },
    ],
    documents: [
      {
        id: 3,
        documentType: 'Resume',
        name: 'Ananya_Iyer_Resume.pdf',
        originalFileName: 'Ananya_Iyer_Resume.pdf',
        uploadedAt: '2026-01-22T09:18:00Z',
        fileSizeBytes: 310000,
        storageUrl: '/mock-documents/resume_ananya.pdf',
      },
    ],
  },
  {
    id: 3,
    candidateCode: 'CND-2026-1003',
    firstName: 'Rohan',
    lastName: 'Verma',
    email: 'rohan.verma@example.com',
    phone: '9711234567',
    gender: 'Male',
    dateOfBirth: '2004-03-15',
    currentLocation: 'Pune, Maharashtra',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Associate Software Engineer (Fresher Drive 2026)',
    vacancyId: 8,
    vacancyTitle: 'Associate Software Engineer (Fresher Drive 2026)',
    experienceYears: 0,
    totalExperienceYears: 0,
    registrationChannel: 'Walk-in',
    currentStage: 'Aptitude Assessment',
    status: 'Rejected',
    highestQualification: 'B.Tech / B.E. (Computer Engineering)',
    institutionName: 'MIT Academy of Engineering',
    yearOfPassing: 2026,
    marksPercentage: 48,
    refType: 'Direct',
    createdAt: '2026-02-01T08:30:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
    pipelineProgress: [
      {
        id: 9,
        roundNumber: 1,
        roundTitle: 'Online Aptitude & Reasoning Elimination',
        roundType: 'Assessment',
        status: 'Failed',
        scoreObtained: 48,
        startedAt: '2026-02-01T09:00:00Z',
        completedAt: '2026-02-01T09:45:00Z',
        candidateExamSessionId: 1005,
        interviewId: null,
      },
      {
        id: 10,
        roundNumber: 2,
        roundTitle: 'Technical Programming Assessment',
        roundType: 'Assessment',
        status: 'Locked',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 11,
        roundNumber: 3,
        roundTitle: 'Technical Interview',
        roundType: 'Interview',
        status: 'Locked',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 12,
        roundNumber: 4,
        roundTitle: 'Director Decision',
        roundType: 'Interview',
        status: 'Locked',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 4,
        documentType: 'Resume',
        name: 'Rohan_Verma_Resume_2026.pdf',
        originalFileName: 'Rohan_Verma_Resume_2026.pdf',
        uploadedAt: '2026-02-01T08:32:00Z',
        fileSizeBytes: 180000,
        storageUrl: '/mock-documents/resume_rohan.pdf',
      },
    ],
  },
  {
    id: 4,
    candidateCode: 'CND-2026-1004',
    firstName: 'Pooja',
    lastName: 'Nair',
    email: 'pooja.nair@example.com',
    phone: '9823456789',
    gender: 'Female',
    dateOfBirth: '1996-11-04',
    currentLocation: 'Bangalore, Karnataka',
    hiringLocation: 'Bangalore Tech Park',
    testLocation: 'Online Remote Proctored',
    role: 'Cloud & DevOps Architect',
    vacancyId: 3,
    vacancyTitle: 'Cloud & DevOps Architect',
    experienceYears: 5.5,
    totalExperienceYears: 5.5,
    registrationChannel: 'Direct',
    currentStage: 'Technical Assessment',
    status: 'In-Progress',
    currentCompany: 'Wipro Technologies',
    currentDesignation: 'Senior DevOps Specialist',
    currentCTC: 19.5,
    expectedCTC: 25,
    noticePeriodDays: 30,
    highestQualification: 'M.Tech in Cloud Computing',
    institutionName: 'IIIT Bangalore',
    yearOfPassing: 2019,
    marksPercentage: 88,
    refType: 'External',
    refName: 'Apex Talent Partners (Kunal Roy)',
    refMobile: '9845019283',
    assignedInterviewer: 'Sunil Rao',
    createdAt: '2026-02-05T11:00:00Z',
    updatedAt: '2026-02-06T15:00:00Z',
    pipelineProgress: [
      {
        id: 13,
        roundNumber: 1,
        roundTitle: 'HR Sourcing & Screening',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 100,
        startedAt: '2026-02-05T11:30:00Z',
        completedAt: '2026-02-05T12:00:00Z',
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 14,
        roundNumber: 2,
        roundTitle: 'Cloud Architecture & Kubernetes Assessment',
        roundType: 'Assessment',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-02-06T14:00:00Z',
        completedAt: null,
        candidateExamSessionId: 1006,
        interviewId: null,
      },
      {
        id: 15,
        roundNumber: 3,
        roundTitle: 'F2F DevOps Deep-Dive Interview',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 16,
        roundNumber: 4,
        roundTitle: 'Director Decision & Offer Rollout',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 5,
        documentType: 'Resume',
        name: 'Pooja_Nair_Cloud_Architect.pdf',
        originalFileName: 'Pooja_Nair_Cloud_Architect.pdf',
        uploadedAt: '2026-02-05T11:05:00Z',
        fileSizeBytes: 290000,
        storageUrl: '/mock-documents/resume_pooja.pdf',
      },
    ],
  },
  {
    id: 5,
    candidateCode: 'CND-2026-1005',
    firstName: 'Karan',
    lastName: 'Mehta',
    email: 'karan.mehta@example.com',
    phone: '9920198765',
    gender: 'Male',
    dateOfBirth: '1994-06-18',
    currentLocation: 'Mumbai, Maharashtra',
    hiringLocation: 'Mumbai HQ',
    testLocation: 'Mumbai Center',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 7,
    totalExperienceYears: 7,
    registrationChannel: 'Walk-in',
    currentStage: 'Hired & Offered',
    status: 'Offered',
    currentCompany: 'TCS Digital',
    currentDesignation: 'Technical Architect',
    currentCTC: 24,
    expectedCTC: 30,
    noticePeriodDays: 30,
    highestQualification: 'B.Tech in Computer Engineering',
    institutionName: 'SPIT Mumbai',
    yearOfPassing: 2016,
    marksPercentage: 84,
    refType: 'Internal',
    refName: 'Vikram Deshmukh',
    refMobile: '9876501122',
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-15T18:00:00Z',
    pipelineProgress: [
      {
        id: 17,
        roundNumber: 1,
        roundTitle: 'Aptitude & General Elimination',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 90,
        startedAt: '2026-01-10T11:00:00Z',
        completedAt: '2026-01-10T11:45:00Z',
        candidateExamSessionId: 1007,
        interviewId: null,
      },
      {
        id: 18,
        roundNumber: 2,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 95,
        startedAt: '2026-01-11T14:00:00Z',
        completedAt: '2026-01-11T15:00:00Z',
        candidateExamSessionId: 1008,
        interviewId: null,
      },
      {
        id: 19,
        roundNumber: 3,
        roundTitle: 'Technical Architecture Interview',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: null,
        startedAt: '2026-01-12T16:00:00Z',
        completedAt: '2026-01-12T17:00:00Z',
        candidateExamSessionId: null,
        interviewId: 2004,
      },
      {
        id: 20,
        roundNumber: 4,
        roundTitle: 'Director & Final Offer Decision',
        roundType: 'Interview',
        status: 'Passed',
        scoreObtained: null,
        startedAt: '2026-01-15T17:00:00Z',
        completedAt: '2026-01-15T17:30:00Z',
        candidateExamSessionId: null,
        interviewId: 2005,
      },
    ],
    documents: [
      {
        id: 6,
        documentType: 'Resume',
        name: 'Karan_Mehta_Architect_CV.pdf',
        originalFileName: 'Karan_Mehta_Architect_CV.pdf',
        uploadedAt: '2026-01-10T10:05:00Z',
        fileSizeBytes: 275000,
        storageUrl: '/mock-documents/resume_karan.pdf',
      },
      {
        id: 7,
        documentType: 'Offer Letter',
        name: 'STEP_Official_Offer_Karan_Mehta.pdf',
        originalFileName: 'STEP_Official_Offer_Karan_Mehta.pdf',
        uploadedAt: '2026-01-15T18:00:00Z',
        fileSizeBytes: 420000,
        storageUrl: '/mock-documents/offer_karan.pdf',
      },
    ],
  },
  {
    id: 6,
    candidateCode: 'CND-2026-1006',
    firstName: 'Divya',
    lastName: 'Choudhary',
    email: 'divya.c@example.com',
    phone: '9819876543',
    gender: 'Female',
    dateOfBirth: '2000-12-10',
    currentLocation: 'Pune, Maharashtra',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'QA Lead & Test Automation Engineer',
    vacancyId: 5,
    vacancyTitle: 'QA Lead & Test Automation Engineer',
    experienceYears: 2.5,
    totalExperienceYears: 2.5,
    registrationChannel: 'Walk-in',
    currentStage: 'Technical Assessment',
    status: 'In-Progress',
    currentCompany: 'Cognizant Technology Solutions',
    currentDesignation: 'QA Automation Engineer',
    currentCTC: 8.5,
    expectedCTC: 12,
    noticePeriodDays: 30,
    highestQualification: 'B.E. in Information Technology',
    institutionName: 'PICT Pune',
    yearOfPassing: 2022,
    marksPercentage: 82,
    refType: 'Direct',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-10T11:30:00Z',
    pipelineProgress: [
      {
        id: 21,
        roundNumber: 1,
        roundTitle: 'Aptitude & Logic Elimination',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 85,
        startedAt: '2026-02-10T09:30:00Z',
        completedAt: '2026-02-10T10:15:00Z',
        candidateExamSessionId: 1009,
        interviewId: null,
      },
      {
        id: 22,
        roundNumber: 2,
        roundTitle: 'Automation & Playwright Test Assessment',
        roundType: 'Assessment',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-02-10T11:00:00Z',
        completedAt: null,
        candidateExamSessionId: 1010,
        interviewId: null,
      },
      {
        id: 23,
        roundNumber: 3,
        roundTitle: 'Technical Interview',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 24,
        roundNumber: 4,
        roundTitle: 'Director Decision',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 8,
        documentType: 'Resume',
        name: 'Divya_Choudhary_QA_CV.pdf',
        originalFileName: 'Divya_Choudhary_QA_CV.pdf',
        uploadedAt: '2026-02-10T09:05:00Z',
        fileSizeBytes: 210000,
        storageUrl: '/mock-documents/resume_divya.pdf',
      },
    ],
  },
  {
    id: 7,
    candidateCode: 'CND-2026-1007',
    firstName: 'Siddharth',
    lastName: 'Kulkarni',
    email: 'siddharth.k@example.com',
    phone: '9867012345',
    gender: 'Male',
    dateOfBirth: '1997-02-28',
    currentLocation: 'Pune, Maharashtra',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Python & AI/ML Engineer',
    vacancyId: 4,
    vacancyTitle: 'Python & AI/ML Engineer',
    experienceYears: 3.5,
    totalExperienceYears: 3.5,
    registrationChannel: 'Direct',
    currentStage: 'Technical Interview',
    status: 'In-Progress',
    currentCompany: 'L&T Infotech',
    currentDesignation: 'AI/ML Software Engineer',
    currentCTC: 14,
    expectedCTC: 18.5,
    noticePeriodDays: 15,
    highestQualification: 'B.Tech in Computer Science',
    institutionName: 'COEP Technological University',
    yearOfPassing: 2021,
    marksPercentage: 90.5,
    refType: 'Internal',
    refName: 'Sneha Joshi',
    refMobile: '9820011223',
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-11T16:00:00Z',
    pipelineProgress: [
      {
        id: 25,
        roundNumber: 1,
        roundTitle: 'HR Sourcing & Screening',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 100,
        startedAt: '2026-02-08T10:30:00Z',
        completedAt: '2026-02-08T11:00:00Z',
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 26,
        roundNumber: 2,
        roundTitle: 'Python & Machine Learning Algorithm Assessment',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 93,
        startedAt: '2026-02-09T14:00:00Z',
        completedAt: '2026-02-09T15:00:00Z',
        candidateExamSessionId: 1011,
        interviewId: null,
      },
      {
        id: 27,
        roundNumber: 3,
        roundTitle: 'AI System Design & Live Coding Interview',
        roundType: 'Interview',
        status: 'In-Progress',
        scoreObtained: null,
        startedAt: '2026-02-11T15:00:00Z',
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: 2006,
      },
      {
        id: 28,
        roundNumber: 4,
        roundTitle: 'Director Decision & Offer Rollout',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 9,
        documentType: 'Resume',
        name: 'Siddharth_Kulkarni_AIML.pdf',
        originalFileName: 'Siddharth_Kulkarni_AIML.pdf',
        uploadedAt: '2026-02-08T10:02:00Z',
        fileSizeBytes: 330000,
        storageUrl: '/mock-documents/resume_siddharth.pdf',
      },
    ],
  },
  {
    id: 8,
    candidateCode: 'CND-2026-1008',
    firstName: 'Aditya',
    lastName: 'Bhange',
    email: 'aditya.bhange@example.com',
    phone: '9876543210',
    gender: 'Male',
    dateOfBirth: '2002-05-15',
    currentLocation: 'Pune, Maharashtra',
    hiringLocation: 'Pune Center (Hinjawadi)',
    testLocation: 'Pune Assessment Hub',
    role: 'Senior .NET Core Architect',
    vacancyId: 1,
    vacancyTitle: 'Senior .NET Core Architect',
    experienceYears: 0,
    totalExperienceYears: 0,
    registrationChannel: 'Walk-in',
    currentStage: 'Technical Assessment',
    status: 'In-Progress',
    highestQualification: 'B.Tech / B.E. (Computer Engineering)',
    institutionName: 'COEP Technological University',
    yearOfPassing: 2026,
    marksPercentage: 85,
    refType: 'Internal',
    refName: 'Rahul Sharma',
    refMobile: '9876501234',
    assignedInterviewer: 'Vikram Deshmukh',
    createdAt: '2026-02-18T09:30:00Z',
    updatedAt: '2026-02-18T11:00:00Z',
    pipelineProgress: [
      {
        id: 29,
        roundNumber: 1,
        roundTitle: 'Aptitude & General Elimination',
        roundType: 'Assessment',
        status: 'Passed',
        scoreObtained: 85,
        startedAt: '2026-02-18T10:00:00Z',
        completedAt: '2026-02-18T10:45:00Z',
        candidateExamSessionId: 1012,
        interviewId: null,
      },
      {
        id: 30,
        roundNumber: 2,
        roundTitle: 'Core .NET & System Design Assessment',
        roundType: 'Assessment',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 31,
        roundNumber: 3,
        roundTitle: 'Technical Architecture Interview',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
      {
        id: 32,
        roundNumber: 4,
        roundTitle: 'Director & Final Offer Decision',
        roundType: 'Interview',
        status: 'Pending',
        scoreObtained: null,
        startedAt: null,
        completedAt: null,
        candidateExamSessionId: null,
        interviewId: null,
      },
    ],
    documents: [
      {
        id: 10,
        documentType: 'Resume',
        name: 'Aditya_Bhange_Resume.pdf',
        originalFileName: 'Aditya_Bhange_Resume.pdf',
        uploadedAt: '2026-02-18T09:32:00Z',
        fileSizeBytes: 240000,
        storageUrl: '/mock-documents/resume_aditya.pdf',
      },
      {
        id: 11,
        documentType: 'Profile Photo',
        name: 'Aditya_Bhange_Photo.jpg',
        originalFileName: 'Aditya_Bhange_Photo.jpg',
        uploadedAt: '2026-02-18T09:30:00Z',
        fileSizeBytes: 150000,
        storageUrl: '',
      },
    ],
  },
];
