import type { InterviewData } from '@/store/services/api';

export const MOCK_INTERVIEWS: Record<number, InterviewData> = {
  2001: {
    id: 2001,
    candidateId: 1,
    candidateName: 'Aarav Sharma',
    vacancyTitle: 'Senior .NET Core Architect',
    interviewerUserId: 4,
    interviewerName: 'Vikram Deshmukh',
    scheduledAt: '2026-01-22T14:30:00Z',
    durationMinutes: 45,
    mode: 'Online',
    meetingLinkOrLocation: 'https://meet.google.com/abc-step-tech',
    status: 'Scheduled',
    roundDetails: [
      {
        id: 301,
        panelistUserId: 4,
        panelistName: 'Vikram Deshmukh',
        technicalRating: 4,
        communicationRating: 4,
        problemSolvingRating: 5,
        culturalFitRating: 4,
        strengths: 'Very solid grasp on C# 13 memory allocation, ref structs, microservices, and CQRS.',
        weaknesses: 'Needs slight exposure to Terraform and multi-region Kubernetes routing.',
        recommendation: 'Hire',
        comments: 'Strongly recommend moving candidate to Director final round.',
        submittedAt: '2026-01-22T15:20:00Z',
      },
    ],
  },
  2002: {
    id: 2002,
    candidateId: 2,
    candidateName: 'Ananya Iyer',
    vacancyTitle: 'Full Stack React / Node Lead Developer',
    interviewerUserId: 4,
    interviewerName: 'Vikram Deshmukh',
    scheduledAt: '2026-01-24T15:00:00Z',
    durationMinutes: 45,
    mode: 'Online',
    meetingLinkOrLocation: 'https://meet.google.com/xyz-step-react',
    status: 'Passed',
    roundDetails: [
      {
        id: 302,
        panelistUserId: 4,
        panelistName: 'Vikram Deshmukh',
        technicalRating: 5,
        communicationRating: 5,
        problemSolvingRating: 4,
        culturalFitRating: 5,
        strengths: 'Exceptional deep dive in React 19 RSC, Redux RTK Query caching tags, and CSS Token systems.',
        weaknesses: 'None observed.',
        recommendation: 'Hire',
        comments: 'High caliber frontend lead candidate. Recommend immediate offer discussions.',
        submittedAt: '2026-01-24T15:50:00Z',
      },
    ],
  },
  2003: {
    id: 2003,
    candidateId: 2,
    candidateName: 'Ananya Iyer',
    vacancyTitle: 'Full Stack React / Node Lead Developer',
    interviewerUserId: 3,
    interviewerName: 'Priya Sharma',
    scheduledAt: '2026-01-26T16:00:00Z',
    durationMinutes: 30,
    mode: 'Online',
    meetingLinkOrLocation: 'https://meet.google.com/sci-hr-round',
    status: 'Scheduled',
    roundDetails: [],
  },
  2004: {
    id: 2004,
    candidateId: 3,
    candidateName: 'Rohan Kulkarni',
    vacancyTitle: 'Senior .NET Core Architect',
    interviewerUserId: 4,
    interviewerName: 'Vikram Deshmukh',
    scheduledAt: '2026-01-20T11:00:00Z',
    durationMinutes: 50,
    mode: 'Onsite',
    meetingLinkOrLocation: 'Mumbai HQ - Conference Room A',
    status: 'Passed',
    roundDetails: [
      {
        id: 303,
        panelistUserId: 4,
        panelistName: 'Vikram Deshmukh',
        technicalRating: 5,
        communicationRating: 4,
        problemSolvingRating: 5,
        culturalFitRating: 5,
        strengths: 'Deep enterprise architecture experience with banking integrations and distributed streaming.',
        weaknesses: 'None',
        recommendation: 'Hire',
        comments: 'Outstanding architecture acumen.',
        submittedAt: '2026-01-20T12:00:00Z',
      },
    ],
  },
  2005: {
    id: 2005,
    candidateId: 3,
    candidateName: 'Rohan Kulkarni',
    vacancyTitle: 'Senior .NET Core Architect',
    interviewerUserId: 2,
    interviewerName: 'Rajesh Kulkarni',
    scheduledAt: '2026-01-24T14:00:00Z',
    durationMinutes: 35,
    mode: 'Onsite',
    meetingLinkOrLocation: 'Mumbai HQ - Executive Boardroom',
    status: 'Passed',
    roundDetails: [
      {
        id: 304,
        panelistUserId: 2,
        panelistName: 'Rajesh Kulkarni',
        technicalRating: 5,
        communicationRating: 5,
        problemSolvingRating: 5,
        culturalFitRating: 5,
        strengths: 'Visionary leadership, strong communication, and cultural alignment with SCIPL values.',
        weaknesses: 'None',
        recommendation: 'Hire',
        comments: 'Approved for senior architecture role. Extend offer letter.',
        submittedAt: '2026-01-24T14:40:00Z',
      },
    ],
  },
  2006: {
    id: 2006,
    candidateId: 5,
    candidateName: 'Devendra Pandey',
    vacancyTitle: 'Cloud DevOps & Kubernetes Specialist',
    interviewerUserId: 7,
    interviewerName: 'Siddharth Rao',
    scheduledAt: '2026-01-15T15:00:00Z',
    durationMinutes: 60,
    mode: 'Online',
    meetingLinkOrLocation: 'https://meet.google.com/devops-deepdive',
    status: 'Passed',
    roundDetails: [
      {
        id: 305,
        panelistUserId: 7,
        panelistName: 'Siddharth Rao',
        technicalRating: 5,
        communicationRating: 4,
        problemSolvingRating: 5,
        culturalFitRating: 4,
        strengths: 'Exceptional hands-on debugging of broken Kubernetes ingress and ArgoCD reconciliation loops.',
        weaknesses: 'None',
        recommendation: 'Hire',
        comments: 'Ready to join team immediately.',
        submittedAt: '2026-01-15T16:10:00Z',
      },
    ],
  },
};
