import type { MasterRecord } from '@/store/services/api';

export const MOCK_MASTER_DATA: Record<string, MasterRecord[]> = {
  roles: [
    {
      id: '1',
      category: 'roles',
      code: 'SNET',
      name: 'Senior .NET Architect',
      description: 'Lead backend enterprise software architect with .NET Core & Cloud expertise',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'roles',
      code: 'FSR',
      name: 'Full Stack React / Node Developer',
      description: 'Modern web frontend and Node.js microservices engineer',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'roles',
      code: 'QA-AUT',
      name: 'QA Automation Lead',
      description: 'End-to-end test automation specialist in Playwright and Selenium',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'roles',
      code: 'DEVOPS',
      name: 'DevOps & Cloud Engineer',
      description: 'Kubernetes, Docker, CI/CD and AWS / Azure cloud infrastructure',
      displayOrder: 4,
      isActive: true,
    },
    {
      id: '5',
      category: 'roles',
      code: 'DATA-ENG',
      name: 'Data Platform Engineer',
      description: 'High-throughput data pipelines, SQL, ETL, and Snowflake/PostgreSQL',
      displayOrder: 5,
      isActive: true,
    },
    {
      id: '6',
      category: 'roles',
      code: 'PROD-MGR',
      name: 'Technical Product Manager',
      description: 'Product roadmap, requirements, user stories, and delivery',
      displayOrder: 6,
      isActive: true,
    },
  ],
  departments: [
    {
      id: '1',
      category: 'departments',
      code: 'ENG',
      name: 'Engineering',
      description: 'Core software engineering, platform development, and architecture',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'departments',
      code: 'QA',
      name: 'Quality Assurance',
      description: 'Testing, automation, quality engineering, and compliance',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'departments',
      code: 'HR',
      name: 'Human Resources',
      description: 'People operations, recruitment, talent acquisition, and employee relations',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'departments',
      code: 'ADMIN',
      name: 'Administration',
      description: 'Executive management and enterprise administration',
      displayOrder: 4,
      isActive: true,
    },
    {
      id: '5',
      category: 'departments',
      code: 'PROD',
      name: 'Product Management',
      description: 'Product lifecycle, design, UI/UX, and business analysis',
      displayOrder: 5,
      isActive: true,
    },
    {
      id: '6',
      category: 'departments',
      code: 'INFRA',
      name: 'Infrastructure & Cloud',
      description: 'Enterprise IT, cloud operations, SRE, and cyber security',
      displayOrder: 6,
      isActive: true,
    },
  ],
  employmenttypes: [
    {
      id: '1',
      category: 'employmenttypes',
      code: 'FTP',
      name: 'Full-Time Permanent',
      description: 'Standard permanent enterprise employment with full benefits',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'employmenttypes',
      code: 'CTH',
      name: 'Contract to Hire',
      description: 'Fixed term contract convertible to permanent position',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'employmenttypes',
      code: 'CONT-6M',
      name: 'Contract (6 Months)',
      description: 'Short-term consulting engagement',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'employmenttypes',
      code: 'INTERN',
      name: 'Internship (Graduate)',
      description: '6-month pre-placement internship program',
      displayOrder: 4,
      isActive: true,
    },
  ],
  hiringlocations: [
    {
      id: '1',
      category: 'hiringlocations',
      code: 'MHQ',
      name: 'Mumbai HQ',
      description: 'Headquarters, Nariman Point, Mumbai',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'hiringlocations',
      code: 'PUN-HINJ',
      name: 'Pune Center (Hinjawadi)',
      description: 'Development center at Hinjawadi Phase 2, Pune',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'hiringlocations',
      code: 'BLR-WF',
      name: 'Bengaluru Tech Hub',
      description: 'Whitefield Technology Park, Bengaluru',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'hiringlocations',
      code: 'HYD-HITEC',
      name: 'Hyderabad Office',
      description: 'HITEC City, Madhapur, Hyderabad',
      displayOrder: 4,
      isActive: true,
    },
  ],
  testlocations: [
    {
      id: '1',
      category: 'testlocations',
      code: 'MCTR',
      name: 'Mumbai Center',
      description: 'On-premise proctored test facility at Mumbai HQ',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'testlocations',
      code: 'PUN-TEST',
      name: 'Pune Assessment Hub',
      description: 'Dedicated high-capacity walk-in test lab, Hinjawadi',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'testlocations',
      code: 'BLR-TEST',
      name: 'Bengaluru Assessment Center',
      description: 'Proctored candidate evaluation terminal lab',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'testlocations',
      code: 'ONLINE-PROCTOR',
      name: 'Online Remote Proctored',
      description: 'Secure browser-locked home assessment portal',
      displayOrder: 4,
      isActive: true,
    },
  ],
  experiencelevels: [
    {
      id: '1',
      category: 'experiencelevels',
      code: 'EXP-0',
      name: 'Fresher (0-1 Years)',
      description: 'Entry level graduate or trainee',
      displayOrder: 1,
      isActive: true,
    },
    {
      id: '2',
      category: 'experiencelevels',
      code: 'EXP-1-3',
      name: 'Junior (1-3 Years)',
      description: 'Associate software engineer / analyst',
      displayOrder: 2,
      isActive: true,
    },
    {
      id: '3',
      category: 'experiencelevels',
      code: 'EXP-3-5',
      name: 'Mid-Level (3-5 Years)',
      description: 'Software Engineer / Test Engineer',
      displayOrder: 3,
      isActive: true,
    },
    {
      id: '4',
      category: 'experiencelevels',
      code: 'EXP-5-8',
      name: 'Senior (5-8 Years)',
      description: 'Senior Software Engineer / Tech Lead',
      displayOrder: 4,
      isActive: true,
    },
    {
      id: '5',
      category: 'experiencelevels',
      code: 'EXP-8PLUS',
      name: 'Lead / Architect (8+ Years)',
      description: 'Principal Architect / Engineering Manager',
      displayOrder: 5,
      isActive: true,
    },
  ],
};
