import type { UserItem } from '@/store/services/api';

export const MOCK_USERS: UserItem[] = [
  {
    id: 1,
    employeeCode: 'EMP-1001',
    firstName: 'System',
    lastName: 'Administrator',
    email: 'admin@sci-pl.com',
    role: 'Administrator',
    department: 'Administration',
    status: 'Active',
  },
  {
    id: 2,
    employeeCode: 'EMP-1002',
    firstName: 'Rajesh',
    lastName: 'Kulkarni',
    email: 'director@sci-pl.com',
    role: 'Director',
    department: 'Administration',
    status: 'Active',
  },
  {
    id: 3,
    employeeCode: 'EMP-1003',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'hr@sci-pl.com',
    role: 'HR',
    department: 'Human Resources',
    status: 'Active',
  },
  {
    id: 4,
    employeeCode: 'EMP-1004',
    firstName: 'Vikram',
    lastName: 'Deshmukh',
    email: 'interviewer@sci-pl.com',
    role: 'Interviewer',
    department: 'Engineering',
    status: 'Active',
  },
  {
    id: 5,
    employeeCode: 'EMP-1005',
    firstName: 'Neha',
    lastName: 'Verma',
    email: 'neha.verma@sci-pl.com',
    role: 'HR',
    department: 'Talent Acquisition',
    status: 'Active',
  },
  {
    id: 6,
    employeeCode: 'EMP-1006',
    firstName: 'Amit',
    lastName: 'Patel',
    email: 'amit.patel@sci-pl.com',
    role: 'Interviewer',
    department: 'Quality Assurance',
    status: 'Active',
  },
  {
    id: 7,
    employeeCode: 'EMP-1007',
    firstName: 'Siddharth',
    lastName: 'Rao',
    email: 'siddharth.rao@sci-pl.com',
    role: 'Interviewer',
    department: 'Engineering',
    status: 'Active',
  },
  {
    id: 8,
    employeeCode: 'EMP-1008',
    firstName: 'Ananya',
    lastName: 'Iyer',
    email: 'ananya.iyer@sci-pl.com',
    role: 'Interviewer',
    department: 'Product Management',
    status: 'Active',
  },
];
